

----------------------------------------------------------------------------
--STAGING TABLES
----------------------------------------------------------------------------
DROP TABLE IF EXISTS OUTCOMES_FACTORS_SUBRANKINGS_STG;
CREATE TABLE OUTCOMES_FACTORS_SUBRANKINGS_STG
(
  FIPS	INTEGER,
  STATE	VARCHAR(250),
  COUNTY VARCHAR(250),
  LNGTH_OF_LF_Z_2019_SCORE DECIMAL(15,2),
  LNGTH_OF_LF_2019_RANK INTEGER,
  QLTY_OF_LF_Z_2019_SCORE DECIMAL(15,2),
  QLTY_OF_LF_2019_RANK INTEGER,
  HLTH_OF_BHVR_Z_2019_SCORE DECIMAL(15,2),
  HLTH_OF_BHVR_2019_RANK INTEGER,
  CLNCL_CR_Z_2019_SCORE DECIMAL(15,2),
  CLNCL_CR_2019_RANK INTEGER,
  SOC_ECO_FCTRS_Z_2019_SCORE DECIMAL(15,2),
  SOC_ECO_FCTRS_2019_RANK INTEGER,
  PHYS_EN_Z_2019_SCORE DECIMAL(15,2),
  PHYS_EN_2019_RANK INTEGER
);
 
DROP TABLE IF EXISTS TRI_FACILITIES_ALL_STG;
CREATE TABLE TRI_FACILITIES_ALL_STG
(
	COLUMN1 VARCHAR(250),
	COLUMN2 VARCHAR(250),
	COLUMN3 VARCHAR(250),
	COLUMN4 VARCHAR(250),
	COLUMN5 VARCHAR(250),
	COLUMN6 VARCHAR(250),
	COLUMN7 VARCHAR(250),
	COLUMN8 INTEGER,
	COLUMN9 VARCHAR(250),
	COLUMN10 VARCHAR(250),
	COLUMN11 VARCHAR(250),
	COLUMN12 DECIMAL(20,5),
	COLUMN13 DECIMAL(20,5)
);


----------------------------------------------------------------------------
--DIMENSION
----------------------------------------------------------------------------
DROP TABLE IF EXISTS FIPS_DIMENSION;
CREATE TABLE FIPS_DIMENSION
(
 FIPS	INTEGER,
 STATE	VARCHAR(250),
 COUNTY VARCHAR(250)
);

 ----------------------------------------------------------------------------
--FACT
----------------------------------------------------------------------------
 DROP TABLE IF EXISTS OUTCOMES_FACTORS_SUBRANKINGS_FACT;
 CREATE TABLE OUTCOMES_FACTORS_SUBRANKINGS_FACT
 (
  FIPS	INTEGER,
  LNGTH_OF_LF_Z_2019_SCORE DECIMAL(15,2),
  LNGTH_OF_LF_2019_RANK INTEGER,
  QLTY_OF_LF_Z_2019_SCORE DECIMAL(15,2),
  QLTY_OF_LF_2019_RANK INTEGER,
  HLTH_OF_BHVR_Z_2019_SCORE DECIMAL(15,2),
  HLTH_OF_BHVR_2019_RANK INTEGER,
  CLNCL_CR_Z_2019_SCORE DECIMAL(15,2),
  CLNCL_CR_2019_RANK INTEGER,
  SOC_ECO_FCTRS_Z_2019_SCORE DECIMAL(15,2),
  SOC_ECO_FCTRS_2019_RANK INTEGER,
  PHYS_EN_Z_2019_SCORE DECIMAL(15,2),
  PHYS_EN_2019_RANK INTEGER,
  TOT_RLS_CUMUL_2016 DECIMAL(15,2),
  TOT_RLS_2016  DECIMAL(15,2),
  SITE_COUNTS_2016  DECIMAL(15,2)
);
 
 
 
 